# Generated by Django 5.1.1 on 2024-09-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_delete_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
