# Generated by Django 5.1.1 on 2024-09-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total_cost',
        ),
    ]
