# Generated by Django 5.1.1 on 2024-09-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_checkout_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
