# Generated by Django 5.1.1 on 2024-09-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_payment_checkout_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='checkout_request_id',
        ),
    ]
